#!/bin/bash
qsub submit_job.sh new_fieldmap_new_sieve/remoll_C12_inelastic_p3_1 0
qsub submit_job.sh new_fieldmap_new_sieve/remoll_C12_inelastic_p3_2 0
qsub submit_job.sh new_fieldmap_new_sieve/remoll_C12_inelastic_p3_3 0
qsub submit_job.sh new_fieldmap_new_sieve/remoll_C12_inelastic_p3_4 0
qsub submit_job.sh new_fieldmap_new_sieve/remoll_C12_inelastic_p3_5 0
